version: "3.9"

services:
  database_rentalx:
    image: postgres
    container_name: database_rentalx
    restart: always
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=rentalx_admin
      - POSTGRES_PASSWORD=rentalx123
      - POSTGRES_DB=rentalx
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: rentalx
    restart: always
    ports: 
      - 3333:3333
      - 9229:9229
    volumes: 
      - .:/usr/app
    links: 
      - database_rentalx
    depends_on:
      - database_rentalx

volumes:
  pgdata:
    driver: local